# Path to your oh-my-zsh installation.
export ZSH="/Users/mcproger/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="sorin"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# pyenv section
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/Users/mcproger/.pyenv/shims:${PATH}"
eval "$(pyenv init -)"

# poetry section
export PATH="/Users/mcproger/.local/bin:$PATH"
export POETRY_VIRTUALENVS_IN_PROJECT="true"


# Zig dev version
export PATH="/Users/mcproger/Work/zig-macos-aarch64-0.14.0:${PATH}"

