tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "bash"
brew "coreutils"
brew "htop"
brew "openssl@3", link: false
brew "pyenv"
brew "vim"
cask "alfred"
cask "discord"
cask "docker"
cask "iterm2"
cask "firefox"
cask "visual-studio-code"